// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.220608.4

void* winrt_make_WinUI3CApp_XamlMetaDataProvider()
{
    return winrt::detach_abi(winrt::make<winrt::WinUI3CApp::factory_implementation::XamlMetaDataProvider>());
}
WINRT_EXPORT namespace winrt::WinUI3CApp
{
    XamlMetaDataProvider::XamlMetaDataProvider() :
        XamlMetaDataProvider(make<WinUI3CApp::implementation::XamlMetaDataProvider>())
    {
    }
}
